{% set version = "0.2.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-waldo
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/waldo_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/waldo/waldo_{{ version }}.tar.gz
  sha256: 1fbab22fe9be6ca8caa3df7306c763d7025d81ab6f17b85daaf8bdc8c9455c53

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-cli
    - r-diffobj
    - r-fansi
    - r-glue
    - r-rematch2
    - r-rlang
    - r-tibble
  run:
    - r-base
    - r-cli
    - r-diffobj
    - r-fansi
    - r-glue
    - r-rematch2
    - r-rlang
    - r-tibble

test:
  commands:
    - $R -e "library('waldo')"           # [not win]
    - "\"%R%\" -e \"library('waldo')\""  # [win]

about:
  home: https://github.com/r-lib/waldo
  license: MIT
  summary: Compare complex R objects and reveal the key differences.  Designed particularly for use in testing packages where being able to quickly isolate key differences makes understanding test failures much easier.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: waldo
# Title: Find Differences Between R Objects
# Version: 0.2.2
# Authors@R: c(person(given = "Hadley", family = "Wickham", role = c("aut", "cre"), email = "hadley@rstudio.com"), person(given = "RStudio", role = "cph"))
# Description: Compare complex R objects and reveal the key differences.  Designed particularly for use in testing packages where being able to quickly isolate key differences makes understanding test failures much easier.
# License: MIT + file LICENSE
# URL: https://github.com/r-lib/waldo
# BugReports: https://github.com/r-lib/waldo/issues
# Imports: cli, diffobj, fansi, glue, methods, rematch2, rlang, tibble
# Suggests: testthat, covr, R6
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 7.1.1
# Config/testthat/edition: 3
# NeedsCompilation: no
# Packaged: 2020-10-15 19:52:48 UTC; hadley
# Author: Hadley Wickham [aut, cre], RStudio [cph]
# Maintainer: Hadley Wickham <hadley@rstudio.com>
# Repository: CRAN
# Date/Publication: 2020-10-15 21:10:02 UTC
